backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
  - name: "puntos"
    label: "Puntos"
    folder:  "content/puntos"
    create: true
    fields:
      - { label: "Nombre", name: "name", widget: "string"}
      - { label: "X", name: 'xCoord', widget: "number"}
      - { label: "Y", name: 'yCoord', widget: "number"}